install.packages("BiocManager", repos="http://cran.us.r-project.org")

BiocManager::install("affy")
BiocManager::install("oligo")
BiocManager::install("Biobase")
BiocManager::install("GEOquery")
BiocManager::install("arrayQualityMetrics")
BiocManager::install("splitstackshape")

library("GEOquery")
library(oligo)
library(Biobase)
library(affy)
library("splitstackshape")
library("tidyr")
library("dplyr")
library("arrayQualityMetrics")
library(limma)
library(vctrs)

setwd("Breast_Cancer")
print("Running Breast Cancer samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
breast_cancer <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(breast_cancer)), file = "breast_cancer_data.csv", row.names = TRUE)



setwd("../Healthy")
print("Running Healthy samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
healthy <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(healthy)), file = "healthy_data.csv", row.names = TRUE)

setwd("../Asthma")
print("Running Asthma samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
asthma <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(asthma)), file = "asthma_data.csv", row.names = TRUE)

setwd("../Hepatocellular_Carcinoma")
print("Running Carcinoma samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
hepatocellular_carcinoma <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(hepatocellular_carcinoma)), file = "hepatocellular_data.csv", row.names = TRUE)

setwd("../Lung_Cancer")
print("Running lung cancer samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
lung_cancer <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(lung_cancer)), file = "lung_cancer_data.csv", row.names = TRUE)

setwd("../Pulmonary_Fibrosis")
print("Running Pulmonary Fibrosis samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
p_fibrosis <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(p_fibrosis)), file = "pulmonary_fibrosis_data.csv", row.names = TRUE)

setwd("../Bladder_Cancer")
print("Running Bladder Cancer samples...")
celFiles <- list.celfiles()
affyRaw <- read.celfiles(celFiles)
bladder_cancer <- oligo::rma(affyRaw)
setwd("../Datasets")
# write.csv(as.data.frame(exprs(bladder_cancer)), file = "bladder_data.csv", row.names = TRUE)
#--------------------------------------------------------------------------------------
setwd("../Differential_Analysis")
pData(breast_cancer)
pData(healthy)
cancerous_expr <- exprs(breast_cancer)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_breast_cancer.csv", row.names = TRUE)
#--------------------------------------------------------------------------------------

pData(asthma)
pData(healthy)
cancerous_expr <- exprs(asthma)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
# write.table(res,"diff_exp.txt", sep="\t")
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_asthma.csv", row.names = TRUE)
#--------------------------------------------------------------------------------------

pData(hepatocellular_carcinoma)
pData(healthy)
cancerous_expr <- exprs(hepatocellular_carcinoma)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
# write.table(res,"diff_exp.txt", sep="\t")
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_hepatocellular_carcinoma.csv", row.names = TRUE)

#--------------------------------------------------------------------------------------

pData(lung_cancer)
pData(healthy)
cancerous_expr <- exprs(lung_cancer)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
# write.table(res,"diff_exp.txt", sep="\t")
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_lung_cancer.csv", row.names = TRUE)

#--------------------------------------------------------------------------------------

pData(p_fibrosis)
pData(healthy)
cancerous_expr <- exprs(p_fibrosis)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
# write.table(res,"diff_exp.txt", sep="\t")
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_pulmonary_fibrosis.csv", row.names = TRUE)

#--------------------------------------------------------------------------------------
pData(bladder_cancer)
pData(healthy)
cancerous_expr <- exprs(bladder_cancer)
non_cancerous_expr <- exprs(healthy)
result <- cbind(cancerous_expr, non_cancerous_expr)


Groups <- factor(c(rep("Cancer", ncol(cancerous_expr)), rep("Normal", ncol(non_cancerous_expr))))
design <- model.matrix(~ Groups)
colnames(design) <- c("Cancer", "CancervsNormal")
fit <- lmFit(result,design)
fit <- eBayes(fit)
options (digits=2)
res <- topTable(fit, number =Inf, adjust.method = "none", coef = 1)
# write.table(res,"diff_exp.txt", sep="\t")
colnames(res) <- c("Gene_ID", "LogFC", "AveExpr", "t", "P.Value", "adj.P.Value")
write.csv(res, "differential_analysis_bladder_cancer.csv", row.names = TRUE)